import { existsSync, mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { runCli } from "../src/cli";

type Event = {
  type: "log" | "warn" | "error";
  message: string;
};

const tempDirs: string[] = [];

afterEach(async () => {
  await Promise.all(tempDirs.map((dir) => rm(dir, { recursive: true, force: true })));
  tempDirs.length = 0;
});

describe("memory-drizzle init CLI", () => {
  it.each([{ argv: [] }, { argv: ["init", "--help"] }, { argv: ["init", "-h"] }])(
    "prints help without writing files for arguments $argv",
    async ({ argv }) => {
      const cwd = createDrizzleProject();
      const events: Event[] = [];

      const code = await runCli(argv, cwd, io(events));

      expect(code).toBe(0);
      expect(messages(events)).toContain("Usage: anvia-memory-drizzle init [options]");
      expect(existsSync(join(cwd, "src/db/anvia-memory.ts"))).toBe(false);
    },
  );

  it.each([
    [["unknown"], "Unknown command: unknown"],
    [["init", "--unknown"], "Unknown option: --unknown"],
    [["init", "--schema"], "--schema requires a path"],
    [["init", "--schema", "--write"], "--schema requires a path"],
  ])("rejects invalid arguments %#", async (argv, expectedMessage) => {
    const cwd = createDrizzleProject();
    const events: Event[] = [];

    const code = await runCli(argv, cwd, io(events));

    expect(code).toBe(1);
    expect(messages(events)).toContain(expectedMessage);
    expect(messages(events)).toContain("Usage: anvia-memory-drizzle init [options]");
  });

  it("reports a missing explicit schema without writing files", async () => {
    const cwd = createDrizzleProject();
    const events: Event[] = [];

    const code = await runCli(
      ["init", "--schema", "missing/schema.ts", "--write"],
      cwd,
      io(events),
    );

    expect(code).toBe(1);
    expect(messages(events)).toContain("Drizzle schema not found at missing/schema.ts");
    expect(existsSync(join(cwd, "missing/anvia-memory.ts"))).toBe(false);
  });

  it("prints a dry-run plan without writing files", async () => {
    const cwd = createDrizzleProject();
    const events: Event[] = [];

    const code = await runCli(["init"], cwd, io(events));

    expect(code).toBe(0);
    expect(existsSync(join(cwd, "src/db/anvia-memory.ts"))).toBe(false);
    expect(messages(events)).toContain("Would create src/db/anvia-memory.ts");
    expect(messages(events)).toContain('from "@anvia/memory-drizzle"');
    expect(messages(events)).toContain("npx drizzle-kit generate");
    expect(messages(events)).toContain("npx drizzle-kit migrate");
  });

  it("writes a generated Drizzle schema export file when --write is passed", async () => {
    const cwd = createDrizzleProject();
    const events: Event[] = [];

    const code = await runCli(["init", "--write"], cwd, io(events));

    expect(code).toBe(0);
    const generated = readFileSync(join(cwd, "src/db/anvia-memory.ts"), "utf8");
    expect(generated).toContain("Generated by @anvia/memory-drizzle");
    expect(generated).toContain("agentMemoryMessages");
    expect(events).toContainEqual({ type: "log", message: "Created src/db/anvia-memory.ts" });
  });

  it("requires --force before overwriting the generated schema file", async () => {
    const cwd = createDrizzleProject();
    await runCli(["init", "--write"], cwd, io([]));
    const events: Event[] = [];

    const code = await runCli(["init", "--write"], cwd, io(events));

    expect(code).toBe(1);
    expect(messages(events)).toContain("already exists");
  });

  it("force-replaces an existing generated schema file", async () => {
    const cwd = createDrizzleProject();
    const generatedPath = join(cwd, "src/db/anvia-memory.ts");
    await runCli(["init", "--write"], cwd, io([]));
    writeFileSync(generatedPath, `${readFileSync(generatedPath, "utf8")}\n// local edit\n`);
    const events: Event[] = [];

    const code = await runCli(["init", "--write", "--force"], cwd, io(events));

    expect(code).toBe(0);
    const generated = readFileSync(generatedPath, "utf8");
    expect(generated).not.toContain("// local edit");
    expect(count(generated, "agentMemorySessions")).toBe(1);
    expect(events).toContainEqual({ type: "log", message: "Updated src/db/anvia-memory.ts" });
  });

  it("does not force-overwrite user-owned files", async () => {
    const cwd = createDrizzleProject();
    writeFileSync(join(cwd, "src/db/anvia-memory.ts"), "// user owned\n");
    const events: Event[] = [];

    const code = await runCli(["init", "--write", "--force"], cwd, io(events));

    expect(code).toBe(1);
    expect(messages(events)).toContain("was not generated by @anvia/memory-drizzle");
  });

  it("warns before appending exports to the existing schema", async () => {
    const cwd = createDrizzleProject();
    const events: Event[] = [];

    const code = await runCli(["init", "--write", "--append-to-schema"], cwd, io(events));

    expect(code).toBe(0);
    expect(events[0]).toMatchObject({
      type: "warn",
      message: expect.stringContaining("appending modifies your existing Drizzle schema"),
    });
    const schema = readFileSync(join(cwd, "src/db/schema.ts"), "utf8");
    expect(schema).toContain("// BEGIN ANVIA MEMORY DRIZZLE SCHEMA");
    expect(schema).toContain("agentMemoryErrors");
  });

  it("requires --force before replacing an existing generated append block", async () => {
    const cwd = createDrizzleProject();
    await runCli(["init", "--write", "--append-to-schema"], cwd, io([]));
    const events: Event[] = [];

    const code = await runCli(["init", "--write", "--append-to-schema"], cwd, io(events));

    expect(code).toBe(1);
    expect(messages(events)).toContain(
      "Anvia memory schema block already exists. Use --force to replace it.",
    );
  });

  it("force-replaces an existing append block without duplicating it", async () => {
    const cwd = createDrizzleProject();
    const schemaPath = join(cwd, "src/db/schema.ts");
    await runCli(["init", "--write", "--append-to-schema"], cwd, io([]));
    writeFileSync(
      schemaPath,
      readFileSync(schemaPath, "utf8").replace(
        "agentMemoryErrors,",
        "// local generated edit\n  agentMemoryErrors,",
      ),
    );
    const events: Event[] = [];

    const code = await runCli(
      ["init", "--write", "--append-to-schema", "--force"],
      cwd,
      io(events),
    );

    expect(code).toBe(0);
    const schema = readFileSync(schemaPath, "utf8");
    expect(schema).not.toContain("// local generated edit");
    expect(count(schema, "// BEGIN ANVIA MEMORY DRIZZLE SCHEMA")).toBe(1);
    expect(messages(events)).toContain("Appended Anvia memory exports to src/db/schema.ts");
  });

  it("fails on incomplete generated append markers", async () => {
    const cwd = createDrizzleProject();
    writeFileSync(
      join(cwd, "src/db/schema.ts"),
      `${baseSchema()}\n// BEGIN ANVIA MEMORY DRIZZLE SCHEMA\n`,
    );
    const events: Event[] = [];

    const code = await runCli(
      ["init", "--write", "--append-to-schema", "--force"],
      cwd,
      io(events),
    );

    expect(code).toBe(1);
    expect(messages(events)).toContain("Found incomplete Anvia memory schema markers");
  });

  it("fails when canonical schema exports already exist outside generated blocks", async () => {
    const cwd = createDrizzleProject();
    writeFileSync(
      join(cwd, "src/db/schema.ts"),
      `${baseSchema()}\nexport const agentMemorySessions = {};\n`,
    );
    const events: Event[] = [];

    const code = await runCli(["init", "--write"], cwd, io(events));

    expect(code).toBe(1);
    expect(messages(events)).toContain(
      "Existing Drizzle schema exports conflict: agentMemorySessions",
    );
  });

  it("does not treat schema identifiers used by neighboring database modules as conflicts", async () => {
    const cwd = createDrizzleProject();
    writeFileSync(
      join(cwd, "src/db/queries.ts"),
      'import { agentMemorySessions } from "./schema";\n',
    );
    const events: Event[] = [];

    const code = await runCli(["init", "--write"], cwd, io(events));

    expect(code).toBe(0);
    expect(existsSync(join(cwd, "src/db/anvia-memory.ts"))).toBe(true);
  });

  it("resolves Drizzle schema directories from --schema", async () => {
    const cwd = createDrizzleProject();
    const events: Event[] = [];

    const code = await runCli(["init", "--schema", "src/db", "--write"], cwd, io(events));

    expect(code).toBe(0);
    expect(existsSync(join(cwd, "src/db/anvia-memory.ts"))).toBe(true);
  });

  it("resolves schema paths from drizzle.config files", async () => {
    const cwd = mkdtempSync(join(tmpdir(), "anvia-memory-drizzle-"));
    tempDirs.push(cwd);
    mkdirSync(join(cwd, "database"), { recursive: true });
    writeFileSync(join(cwd, "database/schema.ts"), baseSchema());
    writeFileSync(
      join(cwd, "drizzle.config.ts"),
      'export default { schema: "database/schema.ts" };\n',
    );
    const events: Event[] = [];

    const code = await runCli(["init", "--write"], cwd, io(events));

    expect(code).toBe(0);
    expect(existsSync(join(cwd, "database/anvia-memory.ts"))).toBe(true);
  });
});

function createDrizzleProject(): string {
  const cwd = mkdtempSync(join(tmpdir(), "anvia-memory-drizzle-"));
  tempDirs.push(cwd);
  mkdirSync(join(cwd, "src/db"), { recursive: true });
  writeFileSync(join(cwd, "src/db/schema.ts"), baseSchema());
  writeFileSync(join(cwd, "drizzle.config.ts"), 'export default { schema: "src/db/schema.ts" };\n');
  return cwd;
}

function baseSchema(): string {
  return 'export const users = { tableName: "users" };\n';
}

function io(events: Event[]) {
  return {
    log(message: string) {
      events.push({ type: "log", message });
    },
    warn(message: string) {
      events.push({ type: "warn", message });
    },
    error(message: string) {
      events.push({ type: "error", message });
    },
  };
}

function messages(events: Event[]): string {
  return events.map((event) => event.message).join("\n");
}

function count(value: string, pattern: string): number {
  return value.split(pattern).length - 1;
}
