packages:
  - "packages/*"
  - "apps/*"
  - "examples/*"
allowBuilds:
  '@google/genai': true
  esbuild: true
  onnxruntime-node: true
  protobufjs: true
  sharp: true
  workerd: true
overrides:
  '@anvia/core': "workspace:*"
patchedDependencies:
  apache-arrow@17.0.0: patches/apache-arrow@17.0.0.patch
packageExtensions:
  apache-arrow@17.0.0:
    bin:
      arrow2csv: bin/arrow2csv.js
