#!/usr/bin/env node
import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import {
  appendEndMarker,
  appendSchemaBlock,
  appendStartMarker,
  generatedSchemaFile,
  generatedSchemaHeader,
  prismaMemoryModelNames,
} from "./schema.js";

type CliOptions = {
  command?: string | undefined;
  schema?: string | undefined;
  write: boolean;
  appendToSchema: boolean;
  force: boolean;
  help: boolean;
};

type CliIo = {
  log(message: string): void;
  warn(message: string): void;
  error(message: string): void;
};

const appendWarning =
  "Warning: appending modifies your existing Prisma schema. Review the generated block before running migrations.";

export async function runCli(
  argv: string[] = process.argv.slice(2),
  cwd = process.cwd(),
  io: CliIo = console,
): Promise<number> {
  let options: CliOptions;
  try {
    options = parseArgs(argv);
  } catch (error) {
    io.error(error instanceof Error ? error.message : String(error));
    io.log(helpText());
    return 1;
  }

  if (options.help || options.command === undefined) {
    io.log(helpText());
    return 0;
  }

  if (options.command !== "init") {
    io.error(`Unknown command: ${options.command}`);
    io.log(helpText());
    return 1;
  }

  try {
    initPrismaMemory(options, cwd, io);
    return 0;
  } catch (error) {
    io.error(error instanceof Error ? error.message : String(error));
    return 1;
  }
}

function initPrismaMemory(options: CliOptions, cwd: string, io: CliIo): void {
  const schemaPath = resolveSchemaPath(cwd, options.schema);
  if (!existsSync(schemaPath)) {
    throw new Error(
      `Prisma schema not found at ${relative(cwd, schemaPath)}. Pass --schema <path> if your schema lives elsewhere.`,
    );
  }

  const targetPath = options.appendToSchema
    ? schemaPath
    : join(dirname(schemaPath), "models", "anvia-memory.prisma");
  const schemaFiles = prismaSchemaFiles(dirname(schemaPath));

  if (options.appendToSchema) {
    io.warn(appendWarning);
  }

  assertNoUnsafeModelConflicts({
    schemaFiles,
    targetPath,
    appendToSchema: options.appendToSchema,
    force: options.force,
  });

  if (options.appendToSchema) {
    appendToSchema(schemaPath, options, cwd, io);
  } else {
    writeGeneratedSchemaFile(targetPath, options, cwd, io);
  }

  io.log("");
  io.log("Next:");
  io.log("  npx prisma validate");
  io.log("  npx prisma migrate dev --name add_anvia_memory");
}

function writeGeneratedSchemaFile(
  targetPath: string,
  options: CliOptions,
  cwd: string,
  io: CliIo,
): void {
  const displayPath = relative(cwd, targetPath);
  const exists = existsSync(targetPath);
  const current = exists ? readFileSync(targetPath, "utf8") : undefined;

  if (current !== undefined && !current.includes(generatedSchemaHeader)) {
    throw new Error(`${displayPath} already exists but was not generated by @anvia/memory-prisma.`);
  }

  if (current !== undefined && !options.force) {
    throw new Error(`${displayPath} already exists. Use --force to overwrite the generated file.`);
  }

  if (!options.write) {
    io.log(`${exists ? "Would overwrite" : "Would create"} ${displayPath}`);
    io.log("");
    io.log(generatedSchemaFile().trimEnd());
    return;
  }

  mkdirSync(dirname(targetPath), { recursive: true });
  writeFileSync(targetPath, `${generatedSchemaFile().trimEnd()}\n`);
  io.log(`${exists ? "Updated" : "Created"} ${displayPath}`);
}

function appendToSchema(schemaPath: string, options: CliOptions, cwd: string, io: CliIo): void {
  const displayPath = relative(cwd, schemaPath);
  const current = readFileSync(schemaPath, "utf8");
  const next = replaceOrAppendBlock(current, options.force);

  if (!options.write) {
    io.log(`Would append Anvia memory models to ${displayPath}`);
    io.log("");
    io.log(appendSchemaBlock());
    return;
  }

  writeFileSync(schemaPath, next);
  io.log(`Appended Anvia memory models to ${displayPath}`);
}

function replaceOrAppendBlock(current: string, force: boolean): string {
  const start = current.indexOf(appendStartMarker);
  const end = current.indexOf(appendEndMarker);
  const block = appendSchemaBlock();

  if (start !== -1 || end !== -1) {
    if (start === -1 || end === -1 || end < start) {
      throw new Error("Found incomplete Anvia memory schema markers in schema.prisma.");
    }
    if (!force) {
      throw new Error("Anvia memory schema block already exists. Use --force to replace it.");
    }
    return `${current.slice(0, start).trimEnd()}\n\n${block}\n${current
      .slice(end + appendEndMarker.length)
      .trimStart()}`;
  }

  return `${current.trimEnd()}\n\n${block}\n`;
}

function assertNoUnsafeModelConflicts(input: {
  schemaFiles: string[];
  targetPath: string;
  appendToSchema: boolean;
  force: boolean;
}): void {
  const normalizedTarget = resolve(input.targetPath);

  for (const file of input.schemaFiles) {
    const content = readFileSync(file, "utf8");
    const normalizedFile = resolve(file);
    const conflictNames = modelConflicts(content);
    if (conflictNames.length === 0) {
      continue;
    }

    if (normalizedFile === normalizedTarget) {
      if (input.appendToSchema && hasGeneratedAppendBlock(content)) {
        const outsideBlock = contentWithoutGeneratedAppendBlock(content);
        const outsideConflicts = modelConflicts(outsideBlock);
        if (outsideConflicts.length > 0) {
          throw new Error(`Existing Prisma models conflict: ${outsideConflicts.join(", ")}`);
        }
        continue;
      }

      if (!input.appendToSchema && content.includes(generatedSchemaHeader)) {
        continue;
      }
    }

    throw new Error(`Existing Prisma models conflict: ${conflictNames.join(", ")}`);
  }
}

function modelConflicts(content: string): string[] {
  return prismaMemoryModelNames.filter((name) =>
    new RegExp(`\\bmodel\\s+${escapeRegExp(name)}\\b`).test(content),
  );
}

function contentWithoutGeneratedAppendBlock(content: string): string {
  const start = content.indexOf(appendStartMarker);
  const end = content.indexOf(appendEndMarker);
  if (start === -1 || end === -1 || end < start) {
    return content;
  }
  return `${content.slice(0, start)}${content.slice(end + appendEndMarker.length)}`;
}

function hasGeneratedAppendBlock(content: string): boolean {
  return content.includes(appendStartMarker) && content.includes(appendEndMarker);
}

function prismaSchemaFiles(schemaDir: string): string[] {
  if (!existsSync(schemaDir)) {
    return [];
  }
  return walk(schemaDir).filter((file) => file.endsWith(".prisma"));
}

function walk(dir: string): string[] {
  return readdirSync(dir).flatMap((name) => {
    const path = join(dir, name);
    return statSync(path).isDirectory() ? walk(path) : [path];
  });
}

function resolveSchemaPath(cwd: string, explicitSchema: string | undefined): string {
  if (explicitSchema !== undefined) {
    return normalizeSchemaPath(resolve(cwd, explicitSchema));
  }

  const configSchema = schemaPathFromPrismaConfig(cwd);
  if (configSchema !== undefined) {
    return configSchema;
  }

  return resolve(cwd, "prisma", "schema.prisma");
}

function schemaPathFromPrismaConfig(cwd: string): string | undefined {
  for (const filename of [
    "prisma.config.ts",
    "prisma.config.mts",
    "prisma.config.js",
    "prisma.config.mjs",
  ]) {
    const path = resolve(cwd, filename);
    if (!existsSync(path)) {
      continue;
    }

    const match = readFileSync(path, "utf8").match(/\bschema\s*:\s*["']([^"']+)["']/);
    if (match?.[1] === undefined) {
      continue;
    }

    return normalizeSchemaPath(resolve(cwd, match[1]));
  }

  return undefined;
}

function normalizeSchemaPath(path: string): string {
  return path.endsWith(".prisma") ? path : join(path, "schema.prisma");
}

function parseArgs(argv: string[]): CliOptions {
  const options: CliOptions = {
    write: false,
    appendToSchema: false,
    force: false,
    help: false,
  };

  const args = [...argv];
  options.command = args.shift();

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    if (arg === "--help" || arg === "-h") {
      options.help = true;
    } else if (arg === "--write") {
      options.write = true;
    } else if (arg === "--append-to-schema") {
      options.appendToSchema = true;
    } else if (arg === "--force") {
      options.force = true;
    } else if (arg === "--schema") {
      const value = args[index + 1];
      if (value === undefined || value.startsWith("-")) {
        throw new Error("--schema requires a path.");
      }
      options.schema = value;
      index += 1;
    } else {
      throw new Error(`Unknown option: ${arg ?? ""}`);
    }
  }

  return options;
}

function helpText(): string {
  return `Usage: anvia-memory-prisma init [options]

Options:
  --schema <path>       Path to schema.prisma or a Prisma schema directory
  --write               Write planned schema changes
  --append-to-schema    Append to schema.prisma instead of creating prisma/models/anvia-memory.prisma
  --force               Overwrite an existing generated Anvia schema file or marker block
  -h, --help            Show help

By default, init is a dry run and prints the schema it would write.`;
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

if (process.argv[1] !== undefined && import.meta.url === `file://${process.argv[1]}`) {
  runCli().then((code) => {
    process.exitCode = code;
  });
}
