export const prismaMemoryModelNames = [
  "AgentMemorySession",
  "AgentMemoryMessage",
  "AgentMemoryError",
] as const;

export const prismaMemorySchema = `model AgentMemorySession {
  id        String   @id @default(cuid())
  scopeKey  String   @unique
  sessionId String
  userId    String?
  metadata  Json
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  messages AgentMemoryMessage[]
  errors   AgentMemoryError[]

  @@index([sessionId, userId])
}

model AgentMemoryMessage {
  id              String             @id @default(cuid())
  memorySessionId String
  memorySession   AgentMemorySession @relation(fields: [memorySessionId], references: [id], onDelete: Cascade)
  runId           String
  turn            Int
  position        Int
  role            String
  message         Json
  createdAt       DateTime           @default(now())

  @@unique([memorySessionId, position])
  @@index([runId])
}

model AgentMemoryError {
  id              String             @id @default(cuid())
  memorySessionId String
  memorySession   AgentMemorySession @relation(fields: [memorySessionId], references: [id], onDelete: Cascade)
  runId           String
  error           Json
  messages        Json
  createdAt       DateTime           @default(now())

  @@index([runId])
}
`;

export const generatedSchemaHeader =
  "// Generated by @anvia/memory-prisma. Review before running Prisma migrations.";

export const appendStartMarker = "// BEGIN ANVIA MEMORY PRISMA MODELS";
export const appendEndMarker = "// END ANVIA MEMORY PRISMA MODELS";

export function generatedSchemaFile(): string {
  return `${generatedSchemaHeader}

${prismaMemorySchema}`;
}

export function appendSchemaBlock(): string {
  return `${appendStartMarker}
${generatedSchemaHeader}

${prismaMemorySchema.trimEnd()}
${appendEndMarker}`;
}
