import { existsSync, mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { runCli } from "../src/cli";

type Event = {
  type: "log" | "warn" | "error";
  message: string;
};

const tempDirs: string[] = [];

afterEach(async () => {
  await Promise.all(tempDirs.map((dir) => rm(dir, { recursive: true, force: true })));
  tempDirs.length = 0;
});

describe("memory-prisma init CLI", () => {
  it.each([
    { argv: [] },
    { argv: ["init", "--help"] },
    { argv: ["init", "-h"] },
  ])("prints help without writing files for arguments $argv", async ({ argv }) => {
    const cwd = createPrismaProject();
    const events: Event[] = [];

    const code = await runCli(argv, cwd, io(events));

    expect(code).toBe(0);
    expect(messages(events)).toContain("Usage: anvia-memory-prisma init [options]");
    expect(existsSync(join(cwd, "prisma/models/anvia-memory.prisma"))).toBe(false);
  });

  it.each([
    [["unknown"], "Unknown command: unknown"],
    [["init", "--unknown"], "Unknown option: --unknown"],
    [["init", "--schema"], "--schema requires a path"],
    [["init", "--schema", "--write"], "--schema requires a path"],
  ])("rejects invalid arguments %#", async (argv, expectedMessage) => {
    const cwd = createPrismaProject();
    const events: Event[] = [];

    const code = await runCli(argv, cwd, io(events));

    expect(code).toBe(1);
    expect(messages(events)).toContain(expectedMessage);
    expect(messages(events)).toContain("Usage: anvia-memory-prisma init [options]");
  });

  it("reports a missing explicit schema without writing files", async () => {
    const cwd = createPrismaProject();
    const events: Event[] = [];

    const code = await runCli(
      ["init", "--schema", "missing/schema.prisma", "--write"],
      cwd,
      io(events),
    );

    expect(code).toBe(1);
    expect(messages(events)).toContain("Prisma schema not found at missing/schema.prisma");
    expect(existsSync(join(cwd, "missing/models/anvia-memory.prisma"))).toBe(false);
  });

  it("prints a dry-run plan without writing files", async () => {
    const cwd = createPrismaProject();
    const events: Event[] = [];

    const code = await runCli(["init"], cwd, io(events));

    expect(code).toBe(0);
    expect(existsSync(join(cwd, "prisma/models/anvia-memory.prisma"))).toBe(false);
    expect(messages(events)).toContain("Would create prisma/models/anvia-memory.prisma");
    expect(messages(events)).toContain("model AgentMemorySession");
    expect(messages(events)).toContain("npx prisma migrate dev --name add_anvia_memory");
  });

  it("writes a multi-file Prisma schema when --write is passed", async () => {
    const cwd = createPrismaProject();
    const events: Event[] = [];

    const code = await runCli(["init", "--write"], cwd, io(events));

    expect(code).toBe(0);
    const generated = readFileSync(join(cwd, "prisma/models/anvia-memory.prisma"), "utf8");
    expect(generated).toContain("Generated by @anvia/memory-prisma");
    expect(generated).toContain("model AgentMemoryMessage");
    expect(messages(events)).toContain("Created prisma/models/anvia-memory.prisma");
  });

  it("requires --force before overwriting the generated schema file", async () => {
    const cwd = createPrismaProject();
    await runCli(["init", "--write"], cwd, io([]));
    const events: Event[] = [];

    const code = await runCli(["init", "--write"], cwd, io(events));

    expect(code).toBe(1);
    expect(messages(events)).toContain("already exists");
  });

  it("force-replaces an existing generated schema file", async () => {
    const cwd = createPrismaProject();
    const generatedPath = join(cwd, "prisma/models/anvia-memory.prisma");
    await runCli(["init", "--write"], cwd, io([]));
    writeFileSync(
      generatedPath,
      `${readFileSync(generatedPath, "utf8")}\n// local generated edit\n`,
    );
    const events: Event[] = [];

    const code = await runCli(["init", "--write", "--force"], cwd, io(events));

    expect(code).toBe(0);
    const generated = readFileSync(generatedPath, "utf8");
    expect(generated).not.toContain("// local generated edit");
    expect(count(generated, "model AgentMemorySession")).toBe(1);
    expect(messages(events)).toContain("Updated prisma/models/anvia-memory.prisma");
  });

  it("does not force-overwrite user-owned files", async () => {
    const cwd = createPrismaProject();
    mkdirSync(join(cwd, "prisma/models"), { recursive: true });
    writeFileSync(join(cwd, "prisma/models/anvia-memory.prisma"), "// user owned\n");
    const events: Event[] = [];

    const code = await runCli(["init", "--write", "--force"], cwd, io(events));

    expect(code).toBe(1);
    expect(messages(events)).toContain("was not generated by @anvia/memory-prisma");
  });

  it("warns before appending to schema.prisma", async () => {
    const cwd = createPrismaProject();
    const events: Event[] = [];

    const code = await runCli(["init", "--write", "--append-to-schema"], cwd, io(events));

    expect(code).toBe(0);
    expect(events[0]).toMatchObject({
      type: "warn",
      message: expect.stringContaining("appending modifies your existing Prisma schema"),
    });
    const schema = readFileSync(join(cwd, "prisma/schema.prisma"), "utf8");
    expect(schema).toContain("// BEGIN ANVIA MEMORY PRISMA MODELS");
    expect(schema).toContain("model AgentMemoryError");
  });

  it("requires --force before replacing an existing generated append block", async () => {
    const cwd = createPrismaProject();
    await runCli(["init", "--write", "--append-to-schema"], cwd, io([]));
    const events: Event[] = [];

    const code = await runCli(["init", "--write", "--append-to-schema"], cwd, io(events));

    expect(code).toBe(1);
    expect(messages(events)).toContain(
      "Anvia memory schema block already exists. Use --force to replace it.",
    );
  });

  it("force-replaces an existing generated append block without duplicating it", async () => {
    const cwd = createPrismaProject();
    await runCli(["init", "--write", "--append-to-schema"], cwd, io([]));
    writeFileSync(
      join(cwd, "prisma/schema.prisma"),
      readFileSync(join(cwd, "prisma/schema.prisma"), "utf8").replace(
        "model AgentMemoryError",
        "// local generated edit\nmodel AgentMemoryError",
      ),
    );
    const events: Event[] = [];

    const code = await runCli(
      ["init", "--write", "--append-to-schema", "--force"],
      cwd,
      io(events),
    );

    expect(code).toBe(0);
    const schema = readFileSync(join(cwd, "prisma/schema.prisma"), "utf8");
    expect(schema).not.toContain("// local generated edit");
    expect(count(schema, "// BEGIN ANVIA MEMORY PRISMA MODELS")).toBe(1);
    expect(messages(events)).toContain("Appended Anvia memory models to prisma/schema.prisma");
  });

  it("fails on incomplete generated append markers", async () => {
    const cwd = createPrismaProject();
    writeFileSync(
      join(cwd, "prisma/schema.prisma"),
      `${baseSchema()}\n// BEGIN ANVIA MEMORY PRISMA MODELS\n`,
    );
    const events: Event[] = [];

    const code = await runCli(
      ["init", "--write", "--append-to-schema", "--force"],
      cwd,
      io(events),
    );

    expect(code).toBe(1);
    expect(messages(events)).toContain("Found incomplete Anvia memory schema markers");
  });

  it("fails when canonical models already exist outside generated blocks", async () => {
    const cwd = createPrismaProject();
    writeFileSync(
      join(cwd, "prisma/schema.prisma"),
      `${baseSchema()}\nmodel AgentMemorySession {\n  id String @id\n}\n`,
    );
    const events: Event[] = [];

    const code = await runCli(["init", "--write"], cwd, io(events));

    expect(code).toBe(1);
    expect(messages(events)).toContain("Existing Prisma models conflict: AgentMemorySession");
  });

  it("resolves Prisma schema directories from --schema", async () => {
    const cwd = createPrismaProject();
    const events: Event[] = [];

    const code = await runCli(["init", "--schema", "prisma", "--write"], cwd, io(events));

    expect(code).toBe(0);
    expect(existsSync(join(cwd, "prisma/models/anvia-memory.prisma"))).toBe(true);
  });

  it("resolves Prisma schema paths from prisma.config files", async () => {
    const cwd = mkdtempSync(join(tmpdir(), "anvia-memory-prisma-"));
    tempDirs.push(cwd);
    mkdirSync(join(cwd, "db"), { recursive: true });
    writeFileSync(join(cwd, "db/schema.prisma"), baseSchema());
    writeFileSync(join(cwd, "prisma.config.ts"), 'export default { schema: "db/schema.prisma" };');
    const events: Event[] = [];

    const code = await runCli(["init", "--write"], cwd, io(events));

    expect(code).toBe(0);
    expect(existsSync(join(cwd, "db/models/anvia-memory.prisma"))).toBe(true);
  });
});

function createPrismaProject(): string {
  const cwd = mkdtempSync(join(tmpdir(), "anvia-memory-prisma-"));
  tempDirs.push(cwd);
  const prismaDir = join(cwd, "prisma");
  mkdirSync(prismaDir, { recursive: true });
  writeFileSync(join(prismaDir, "schema.prisma"), baseSchema());
  return cwd;
}

function baseSchema(): string {
  return `generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
}
`;
}

function io(events: Event[]) {
  return {
    log(message: string) {
      events.push({ type: "log", message });
    },
    warn(message: string) {
      events.push({ type: "warn", message });
    },
    error(message: string) {
      events.push({ type: "error", message });
    },
  };
}

function messages(events: Event[]): string {
  return events.map((event) => event.message).join("\n");
}

function count(value: string, pattern: string): number {
  return value.split(pattern).length - 1;
}
