#!/usr/bin/env node
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, extname, join, relative, resolve } from "node:path";
import {
  appendEndMarker,
  appendSchemaBlock,
  appendStartMarker,
  drizzleMemoryExportNames,
  generatedSchemaFile,
  generatedSchemaHeader,
} from "./generated-schema.js";

type CliOptions = {
  command?: string | undefined;
  schema?: string | undefined;
  write: boolean;
  appendToSchema: boolean;
  force: boolean;
  help: boolean;
};

type CliIo = {
  log(message: string): void;
  warn(message: string): void;
  error(message: string): void;
};

const appendWarning =
  "Warning: appending modifies your existing Drizzle schema. Review the generated block before running migrations.";

const schemaExtensions = new Set([".ts", ".js", ".mts", ".mjs", ".cts", ".cjs"]);

export async function runCli(
  argv: string[] = process.argv.slice(2),
  cwd = process.cwd(),
  io: CliIo = console,
): Promise<number> {
  let options: CliOptions;
  try {
    options = parseArgs(argv);
  } catch (error) {
    io.error(error instanceof Error ? error.message : String(error));
    io.log(helpText());
    return 1;
  }

  if (options.help || options.command === undefined) {
    io.log(helpText());
    return 0;
  }

  if (options.command !== "init") {
    io.error(`Unknown command: ${options.command}`);
    io.log(helpText());
    return 1;
  }

  try {
    initDrizzleMemory(options, cwd, io);
    return 0;
  } catch (error) {
    io.error(error instanceof Error ? error.message : String(error));
    return 1;
  }
}

function initDrizzleMemory(options: CliOptions, cwd: string, io: CliIo): void {
  const schemaPath = resolveSchemaPath(cwd, options.schema);
  if (!existsSync(schemaPath)) {
    throw new Error(
      `Drizzle schema not found at ${relative(cwd, schemaPath)}. Pass --schema <path> if your schema lives elsewhere.`,
    );
  }

  const targetPath = options.appendToSchema
    ? schemaPath
    : join(dirname(schemaPath), "anvia-memory.ts");
  const schemaFiles = [...new Set([schemaPath, targetPath])].filter((path) => existsSync(path));

  if (options.appendToSchema) {
    io.warn(appendWarning);
  }

  assertNoUnsafeSchemaConflicts({
    schemaFiles,
    targetPath,
    appendToSchema: options.appendToSchema,
  });

  if (options.appendToSchema) {
    appendToSchema(schemaPath, options, cwd, io);
  } else {
    writeGeneratedSchemaFile(targetPath, options, cwd, io);
  }

  io.log("");
  io.log("Next:");
  if (!options.appendToSchema) {
    io.log(
      `  Ensure ${relative(cwd, targetPath)} is included by the schema setting in drizzle.config.ts`,
    );
  }
  io.log("  npx drizzle-kit generate");
  io.log("  npx drizzle-kit migrate");
}

function writeGeneratedSchemaFile(
  targetPath: string,
  options: CliOptions,
  cwd: string,
  io: CliIo,
): void {
  const displayPath = relative(cwd, targetPath);
  const exists = existsSync(targetPath);
  const current = exists ? readFileSync(targetPath, "utf8") : undefined;

  if (current !== undefined && !current.includes(generatedSchemaHeader)) {
    throw new Error(
      `${displayPath} already exists but was not generated by @anvia/memory-drizzle.`,
    );
  }

  if (current !== undefined && !options.force) {
    throw new Error(`${displayPath} already exists. Use --force to overwrite the generated file.`);
  }

  if (!options.write) {
    io.log(`${exists ? "Would overwrite" : "Would create"} ${displayPath}`);
    io.log("");
    io.log(generatedSchemaFile().trimEnd());
    return;
  }

  mkdirSync(dirname(targetPath), { recursive: true });
  writeFileSync(targetPath, generatedSchemaFile());
  io.log(`${exists ? "Updated" : "Created"} ${displayPath}`);
}

function appendToSchema(schemaPath: string, options: CliOptions, cwd: string, io: CliIo): void {
  const displayPath = relative(cwd, schemaPath);
  const current = readFileSync(schemaPath, "utf8");
  const next = replaceOrAppendBlock(current, options.force);

  if (!options.write) {
    io.log(`Would append Anvia memory exports to ${displayPath}`);
    io.log("");
    io.log(appendSchemaBlock());
    return;
  }

  writeFileSync(schemaPath, next);
  io.log(`Appended Anvia memory exports to ${displayPath}`);
}

function replaceOrAppendBlock(current: string, force: boolean): string {
  const start = current.indexOf(appendStartMarker);
  const end = current.indexOf(appendEndMarker);
  const block = appendSchemaBlock();

  if (start !== -1 || end !== -1) {
    if (start === -1 || end === -1 || end < start) {
      throw new Error("Found incomplete Anvia memory schema markers in the Drizzle schema.");
    }
    if (!force) {
      throw new Error("Anvia memory schema block already exists. Use --force to replace it.");
    }
    return `${current.slice(0, start).trimEnd()}\n\n${block}\n${current
      .slice(end + appendEndMarker.length)
      .trimStart()}`;
  }

  return `${current.trimEnd()}\n\n${block}\n`;
}

function assertNoUnsafeSchemaConflicts(input: {
  schemaFiles: string[];
  targetPath: string;
  appendToSchema: boolean;
}): void {
  const normalizedTarget = resolve(input.targetPath);

  for (const file of input.schemaFiles) {
    const content = readFileSync(file, "utf8");
    const normalizedFile = resolve(file);
    const conflictNames = schemaConflicts(content);
    if (conflictNames.length === 0) {
      continue;
    }

    if (normalizedFile === normalizedTarget) {
      if (input.appendToSchema && hasGeneratedAppendBlock(content)) {
        const outsideBlock = contentWithoutGeneratedAppendBlock(content);
        const outsideConflicts = schemaConflicts(outsideBlock);
        if (outsideConflicts.length > 0) {
          throw new Error(
            `Existing Drizzle schema exports conflict: ${outsideConflicts.join(", ")}`,
          );
        }
        continue;
      }

      if (!input.appendToSchema && content.includes(generatedSchemaHeader)) {
        continue;
      }
    }

    throw new Error(`Existing Drizzle schema exports conflict: ${conflictNames.join(", ")}`);
  }
}

function schemaConflicts(content: string): string[] {
  return drizzleMemoryExportNames.filter((name) => new RegExp(`\\b${name}\\b`).test(content));
}

function contentWithoutGeneratedAppendBlock(content: string): string {
  const start = content.indexOf(appendStartMarker);
  const end = content.indexOf(appendEndMarker);
  if (start === -1 || end === -1 || end < start) {
    return content;
  }
  return `${content.slice(0, start)}${content.slice(end + appendEndMarker.length)}`;
}

function hasGeneratedAppendBlock(content: string): boolean {
  return content.includes(appendStartMarker) && content.includes(appendEndMarker);
}

function resolveSchemaPath(cwd: string, explicitSchema: string | undefined): string {
  if (explicitSchema !== undefined) {
    return normalizeSchemaPath(resolve(cwd, explicitSchema));
  }

  const configSchema = schemaPathFromDrizzleConfig(cwd);
  if (configSchema !== undefined) {
    return configSchema;
  }

  return resolve(cwd, "src", "db", "schema.ts");
}

function schemaPathFromDrizzleConfig(cwd: string): string | undefined {
  for (const filename of [
    "drizzle.config.ts",
    "drizzle.config.mts",
    "drizzle.config.js",
    "drizzle.config.mjs",
  ]) {
    const path = resolve(cwd, filename);
    if (!existsSync(path)) {
      continue;
    }

    const match = readFileSync(path, "utf8").match(/\bschema\s*:\s*["']([^"']+)["']/);
    if (match?.[1] === undefined || containsGlob(match[1])) {
      continue;
    }

    return normalizeSchemaPath(resolve(cwd, match[1]));
  }

  return undefined;
}

function normalizeSchemaPath(path: string): string {
  return schemaExtensions.has(extname(path)) ? path : join(path, "schema.ts");
}

function containsGlob(path: string): boolean {
  return /[*?{}[\]]/.test(path);
}

function parseArgs(argv: string[]): CliOptions {
  const options: CliOptions = {
    write: false,
    appendToSchema: false,
    force: false,
    help: false,
  };

  const args = [...argv];
  options.command = args.shift();

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    if (arg === "--help" || arg === "-h") {
      options.help = true;
    } else if (arg === "--write") {
      options.write = true;
    } else if (arg === "--append-to-schema") {
      options.appendToSchema = true;
    } else if (arg === "--force") {
      options.force = true;
    } else if (arg === "--schema") {
      const value = args[index + 1];
      if (value === undefined || value.startsWith("-")) {
        throw new Error("--schema requires a path.");
      }
      options.schema = value;
      index += 1;
    } else {
      throw new Error(`Unknown option: ${arg ?? ""}`);
    }
  }

  return options;
}

function helpText(): string {
  return `Usage: anvia-memory-drizzle init [options]

Options:
  --schema <path>       Path to a Drizzle schema file or directory
  --write               Write planned schema changes
  --append-to-schema    Append exports to the existing schema instead of creating anvia-memory.ts
  --force               Overwrite an existing generated Anvia schema file or marker block
  -h, --help            Show help

By default, init is a dry run and prints the schema export file it would write.`;
}

if (process.argv[1] !== undefined && import.meta.url === `file://${process.argv[1]}`) {
  runCli().then((code) => {
    process.exitCode = code;
  });
}
