export const drizzleMemoryExportNames = [
  "agentMemoryErrors",
  "agentMemoryMessages",
  "agentMemorySessions",
] as const;

export const generatedSchemaHeader =
  "// Generated by @anvia/memory-drizzle. Review before running Drizzle migrations.";

export const appendStartMarker = "// BEGIN ANVIA MEMORY DRIZZLE SCHEMA";
export const appendEndMarker = "// END ANVIA MEMORY DRIZZLE SCHEMA";

export function generatedSchemaFile(): string {
  return `${generatedSchemaHeader}

${schemaExportBlock()}
`;
}

export function appendSchemaBlock(): string {
  return `${appendStartMarker}
${generatedSchemaHeader}

${schemaExportBlock()}
${appendEndMarker}`;
}

function schemaExportBlock(): string {
  return `export {
  agentMemoryErrors,
  agentMemoryMessages,
  agentMemorySessions,
} from "@anvia/memory-drizzle";`;
}
